version: doc"3"

services:
  api-covidstat:
    build: .
    # specifying the image-name for the image built using dockerfile
    image: "casestudy_covidstat"
    container_name: "covidstat_service"
    networks:
      - casestudy
    ports:
      - "8080:8080"

networks:
  casestudy:
    external: true