# in minutes
cache:
  ttl:
    latestStatCountry: 35
    oneDayPrevious: 1440
    twoDayPrevious: 2880
    vaccineCoverageTrends: 7200
    alertMessage: 35

  host: localhost
  port: 6379

api:
  key: 3f5c6d0e-9f48-4d5c-ae78-2db63e2f8c41

supportedCountries:
  - Afghanistan
  - Albania
  - Algeria
  - Andorra
  - Angola
  - Antarctica
  - Antigua and Barbuda
  - Argentina
  - Armenia
  - Australia
  - Austria
  - Azerbaijan
  - Bahamas
  - Bahrain
  - Bangladesh
  - Barbados
  - Belarus
  - Belgium
  - Belize
  - Benin
  - Bhutan
  - Bolivia
  - Bosnia
  - Botswana
  - Brazil
  - Brunei
  - Bulgaria
  - Burkina Faso
  - Burma
  - Burundi
  - Cabo Verde
  - Cambodia
  - Cameroon
  - Canada
  - Central African Republic
  - Chad
  - Chile
  - China
  - Colombia
  - Comoros
  - Congo
  - Costa Rica
  - "CÃ´te d'Ivoire"
  - Croatia
  - Cuba
  - Cyprus
  - Czechia
  - Denmark
  - Diamond Princess
  - Djibouti
  - Dominica
  - Dominican Republic
  - DRC
  - Ecuador
  - Egypt
  - El Salvador
  - Equatorial Guinea
  - Eritrea
  - Estonia
  - Ethiopia
  - Fiji
  - Finland
  - France
  - Gabon
  - Gambia
  - Georgia
  - Germany
  - Ghana
  - Greece
  - Grenada
  - Guatemala
  - Guinea-Bissau
  - Guinea
  - Guyana
  - Haiti
  - Holy See
  - Honduras
  - Hungary
  - Iceland
  - India
  - Indonesia
  - Iran
  - Iraq
  - Ireland
  - Israel
  - Italy
  - Jamaica
  - Japan
  - Jordan
  - Kazakhstan
  - Kenya
  - Kiribati
  - Kosovo
  - Kuwait
  - Kyrgyzstan
  - "Lao People's Democratic Republic"
  - Latvia
  - Lebanon
  - Lesotho
  - Liberia
  - Libyan Arab Jamahiriya
  - Liechtenstein
  - Lithuania
  - Luxembourg
  - Macedonia
  - Madagascar
  - Malawi
  - Malaysia
  - Maldives
  - Mali
  - Malta
  - Marshall Islands
  - Mauritania
  - Mauritius
  - Mexico
  - Micronesia
  - Moldova
  - Monaco
  - Mongolia
  - Montenegro
  - Morocco
  - Mozambique
  - MS Zaandam
  - N. Korea
  - Namibia
  - Nauru
  - Nepal
  - Netherlands
  - New Zealand
  - Nicaragua
  - Niger
  - Nigeria
  - Norway
  - Oman
  - Pakistan
  - Palau
  - Panama
  - Papua New Guinea
  - Paraguay
  - Peru
  - Philippines
  - Poland
  - Portugal
  - Qatar
  - Romania
  - Russia
  - Rwanda
  - S. Korea
  - Saint Kitts and Nevis
  - Saint Lucia
  - Saint Vincent and the Grenadines
  - Samoa
  - San Marino
  - Sao Tome and Principe
  - Saudi Arabia
  - Senegal
  - Serbia
  - Seychelles
  - Sierra Leone
  - Singapore
  - Slovakia
  - Slovenia
  - Solomon Islands
  - Somalia
  - South Africa
  - South Sudan
  - Spain
  - Sri Lanka
  - Sudan
  - Summer Olympics 2020
  - Suriname
  - Swaziland
  - Sweden
  - Switzerland
  - Syrian Arab Republic
  - Taiwan
  - Tajikistan
  - Tanzania
  - Thailand
  - Timor-Leste
  - Togo
  - Tonga
  - Trinidad and Tobago
  - Tunisia
  - Turkey
  - Tuvalu
  - UAE
  - Uganda
  - UK
  - Ukraine
  - Uruguay
  - USA
  - Uzbekistan
  - Vanuatu
  - Venezuela
  - Vietnam
  - West Bank and Gaza
  - Winter Olympics 2022
  - Yemen
  - Zambia
  - Zimbabwe